# 予測時のパラメータをyamlで指定する
#
#
#
#

mode: predict

location:
  data_path: "data/test_data"
  config_path: "config/transformer_encoder/test.yaml"

predict:
  # モデルのパラメータ
  d_model: 512
  n_head: 8
  num_encoder_layer: 8
  dropout: 0.2

  # 損失関数パラメータ
  loss_alpha: 1.0
  loss_beta: 0.1

  # 重みファイルのパス
  checkpoint_file: './weight/best_skeleton_model.pth'
