# 予測時のパラメータをyamlで指定する
#
#
#
#

mode: predict

location:
  data_path: "data/test_data"
  config_path: "config/transformer_encoder/test.yaml"

predict:
  # model
  d_model: 512
  n_head: 8
  num_encoder_layer: 8
  dropout: 0.2
  batch_size: 128
  sequence_len: 50

  # check point file path
  checkpoint_file: './weight/best_skeleton_model.pth'
