# 学習時のパラメータ用のYAML
#
#
#
#

mode: train

location:
  data_path: "data/training_data"
  config_path: "config/transformer_encoder/train.yaml"

train:
  # model
  d_model: 512
  n_head: 8
  num_encoder_layer: 8
  dropout: 0.2

  # train
  epoch: 100
  batch_size: 64

  # optimize
  learning_rate: 0.0005
  weight_decay: 0.001

  # Loss fanction
  loss_alpha: 1.0
  loss_beta: 0.1

  # others
  sequence_len: 60
  use_gradient_data: False
